stages:
  - publish

publish:
  stage: publish
  image: node:latest
  script:
    - sed -i s/0.0.0/$CI_COMMIT_TAG/g package.json
    - yarn
    - yarn build
    - echo '//gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}'>.npmrc
    - npm publish
  only:
    - tags
