name: Build and Deploy Documentation
on: [push]
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Deploy docs
        uses: jenkey2011/vuepress-deploy@master
        env:
          ACCESS_TOKEN: ${{ secrets.PAT }}
          TARGET_REPO: kratosgg/ventricle
          TARGET_BRANCH: gh-pages
          BUILD_SCRIPT: yarn && yarn vuepress:build
          BUILD_DIR: docs/.vuepress/dist/
          CNAME: docs.kratos.gg